# Site settings
title: Artemit
description: >
  Artemit provides startups, non-profits, and larger corporations with
  a skilled network of experts dedicated to starting your venture,
  building your new concepts, and revamping your existing projects.
baseurl: "/"
url: "http://artemit.com"
organization: Artemit LLC

sass:
  sass_dir: /assets/_sass
  style: compressed

exclude:
  - Gemfile
