title: Artemit
description: >
  Artemit provides startups, non-profits, and corporations with a skilled 
  network of experts dedicated to rapidly starting their new ventures,
  building their projects, and expanding their global outreach.
url: "http://artemit.com"
organization: Artemit LLC

sass:
  sass_dir: /assets/_sass
  style: compressed

gems:
  - jekyll-sitemap

exclude:
  - Gemfile
