title: Artemit
description: >
  Artemit provides startups, non-profits, and corporations a skilled 
  network of experts dedicated to rapidly starting their venture,
  building their new concepts, and revamping their existing projects.
url: "http://artemit.com"
organization: Artemit LLC

sass:
  sass_dir: /assets/_sass
  style: compressed

gems:
  - jekyll-sitemap

exclude:
  - Gemfile
